version: '3.7'

services:
  database:
    image: postgres
    container_name: templete
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=templete
      - POSTGRES_PASSWORD=templete
      - POSTGRES_DB=templete
    volumes:
      - pgdata:/data/postgres

    network_mode: host

  app:
    build: .
    container_name: templex
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
  pgdata:
    driver: local
